wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 8
max_epoch:
  desc: null
  value: 5
architecture:
  desc: null
  value: EAST
dataset:
  desc: null
  value: EASTDataset
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706166016.245234
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.5
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
